export enum ErrorCode {
  // Generic errors
  UNKNOWN = "UNKNOWN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNSUPPORTED_API_VERSION = "UNSUPPORTED_API_VERSION",

  // Resource errors
  NOT_FOUND = "NOT_FOUND",
  TOURNAMENT_NOT_FOUND = "TOURNAMENT_NOT_FOUND",
  MATCH_NOT_FOUND = "MATCH_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  TEAM_NOT_FOUND = "TEAM_NOT_FOUND",
  DISCIPLINE_NOT_FOUND = "DISCIPLINE_NOT_FOUND",
  OUTCOME_TYPE_NOT_FOUND = "OUTCOME_TYPE_NOT_FOUND",
  OUTCOME_REASON_NOT_FOUND = "OUTCOME_REASON_NOT_FOUND",

  // Discipline / outcome archiving errors
  DISCIPLINE_IN_USE = "DISCIPLINE_IN_USE",
  DISCIPLINE_ALREADY_ARCHIVED = "DISCIPLINE_ALREADY_ARCHIVED",
  DISCIPLINE_NOT_ARCHIVED = "DISCIPLINE_NOT_ARCHIVED",
  OUTCOME_TYPE_IN_USE = "OUTCOME_TYPE_IN_USE",
  OUTCOME_TYPE_ALREADY_ARCHIVED = "OUTCOME_TYPE_ALREADY_ARCHIVED",
  OUTCOME_TYPE_NOT_ARCHIVED = "OUTCOME_TYPE_NOT_ARCHIVED",
  OUTCOME_REASON_IN_USE = "OUTCOME_REASON_IN_USE",
  RESOURCE_IN_USE = "RESOURCE_IN_USE",

  // Permission errors
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

  // Business logic errors - Tournament
  TOURNAMENT_INVALID_STATUS = "TOURNAMENT_INVALID_STATUS",
  TOURNAMENT_CLOSED = "TOURNAMENT_CLOSED",
  TOURNAMENT_CANNOT_BE_DELETED = "TOURNAMENT_CANNOT_BE_DELETED",
  TOURNAMENT_FIELD_UPDATE_FORBIDDEN = "TOURNAMENT_FIELD_UPDATE_FORBIDDEN",
  TOURNAMENT_FIELD_LOCKED_BY_MATCHES = "TOURNAMENT_FIELD_LOCKED_BY_MATCHES",
  TOURNAMENT_NAME_ALREADY_EXISTS = "TOURNAMENT_NAME_ALREADY_EXISTS",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  INVALID_TEAM_SIZE = "INVALID_TEAM_SIZE",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
  MAX_DRAFT_TOURNAMENTS_EXCEEDED = "MAX_DRAFT_TOURNAMENTS_EXCEEDED",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  NOT_REGISTERED = "NOT_REGISTERED",
  CANNOT_LEAVE_ONGOING_TOURNAMENT = "CANNOT_LEAVE_ONGOING_TOURNAMENT",

  // Business logic errors - Match
  MATCH_INVALID_STATUS = "MATCH_INVALID_STATUS",
  MATCH_ALREADY_CONFIRMED = "MATCH_ALREADY_CONFIRMED",
  MATCH_ALREADY_FINALIZED = "MATCH_ALREADY_FINALIZED",
  MATCH_CANNOT_BE_DELETED = "MATCH_CANNOT_BE_DELETED",
  MATCH_CANNOT_BE_CANCELLED = "MATCH_CANNOT_BE_CANCELLED",
  CANCEL_WINDOW_EXPIRED = "CANCEL_WINDOW_EXPIRED",
  MATCH_INVALID_TEAMS = "MATCH_INVALID_TEAMS",
  MATCH_INVALID_PLAYERS = "MATCH_INVALID_PLAYERS",
  MATCH_DUPLICATE_TEAMS = "MATCH_DUPLICATE_TEAMS",
  MATCH_OVERLAPPING_PLAYERS = "MATCH_OVERLAPPING_PLAYERS",
  MATCH_INVALID_SCORE = "MATCH_INVALID_SCORE",
  MATCH_DRAW_NOT_ALLOWED = "MATCH_DRAW_NOT_ALLOWED",
  MATCH_SCORE_OUT_OF_RANGE = "MATCH_SCORE_OUT_OF_RANGE",
  MATCH_WINNER_REQUIRED = "MATCH_WINNER_REQUIRED",
  MATCH_SAME_REPORTER_CONFIRMER = "MATCH_SAME_REPORTER_CONFIRMER",
  MATCH_TEAM_SIZE_MISMATCH = "MATCH_TEAM_SIZE_MISMATCH",
  PLAYER_SCHEDULE_CONFLICT = "PLAYER_SCHEDULE_CONFLICT",

  // Constraint violations
  MAX_MATCHES_EXCEEDED = "MAX_MATCHES_EXCEEDED",
  ALL_PLAYERS_MAX_MATCHES_EXCEEDED = "ALL_PLAYERS_MAX_MATCHES_EXCEEDED",
  MAX_PARTNER_MATCHES_EXCEEDED = "MAX_PARTNER_MATCHES_EXCEEDED",
  MAX_OPPONENT_MATCHES_EXCEEDED = "MAX_OPPONENT_MATCHES_EXCEEDED",


  // Participant errors
  NOT_A_PARTICIPANT = "NOT_A_PARTICIPANT",
  PLAYER_NOT_IN_TOURNAMENT = "PLAYER_NOT_IN_TOURNAMENT",
  TEAM_NOT_IN_TOURNAMENT = "TEAM_NOT_IN_TOURNAMENT",

  // Bracket errors
  INVALID_TOURNAMENT_MODE = "INVALID_TOURNAMENT_MODE",
  BRACKET_CANNOT_REGENERATE = "BRACKET_CANNOT_REGENERATE",
  BRACKET_MATCH_TEAMS_NOT_READY = "BRACKET_MATCH_TEAMS_NOT_READY",
  SOURCE_TOURNAMENT_NOT_FOUND = "SOURCE_TOURNAMENT_NOT_FOUND",
  SOURCE_TOURNAMENT_NOT_FINISHED = "SOURCE_TOURNAMENT_NOT_FINISHED",
  DISCIPLINE_MISMATCH = "DISCIPLINE_MISMATCH",
  INSUFFICIENT_PARTICIPANTS = "INSUFFICIENT_PARTICIPANTS",
  CHAMPIONSHIP_PARTICIPANTS_WITHOUT_MATCHES = "CHAMPIONSHIP_PARTICIPANTS_WITHOUT_MATCHES",

  // Team errors
  TEAM_FULL = "TEAM_FULL",
  TEAM_NAME_TAKEN = "TEAM_NAME_TAKEN",
  PLAYER_ALREADY_IN_TEAM = "PLAYER_ALREADY_IN_TEAM",
  PLAYER_NOT_IN_TEAM = "PLAYER_NOT_IN_TEAM",
  TEAM_SIZE_INVALID = "TEAM_SIZE_INVALID",
  TEAM_HAS_MATCH = "TEAM_HAS_MATCH",

  // Game rules errors
  GAME_RULE_NOT_FOUND = "GAME_RULE_NOT_FOUND",

  // Rules engine errors
  RANDOM_NOT_ALLOWED_ON_BADGE = "RANDOM_NOT_ALLOWED_ON_BADGE",
  INVALID_OPERATOR_FOR_FACT = "INVALID_OPERATOR_FOR_FACT",

  // Ranked errors
  SEASON_ALREADY_ACTIVE = "SEASON_ALREADY_ACTIVE",
  SEASON_NOT_FOUND = "SEASON_NOT_FOUND",
  RANKED_MATCH_TOO_OLD = "RANKED_MATCH_TOO_OLD",
  RANK_TIER_NOT_FOUND = "RANK_TIER_NOT_FOUND",
  INVALID_RANK_TIER_LEVEL = "INVALID_RANK_TIER_LEVEL",
  REWIND_NOT_FOUND = "REWIND_NOT_FOUND",
  REWIND_VERSION_FROZEN = "REWIND_VERSION_FROZEN",

  // Post-finalization dispute errors
  DISPUTE_NOT_ALLOWED_FOR_VALIDATION_MODE = "DISPUTE_NOT_ALLOWED_FOR_VALIDATION_MODE",
  DISPUTE_WINDOW_EXPIRED = "DISPUTE_WINDOW_EXPIRED",
  ALREADY_DISPUTED = "ALREADY_DISPUTED",
  CANNOT_AGREE_AFTER_FINALIZATION = "CANNOT_AGREE_AFTER_FINALIZATION",

  // Notification errors
  NOTIFICATION_ACTION_PENDING = "NOTIFICATION_ACTION_PENDING",

  // Match discussion thread errors
  MATCH_MESSAGE_INVALID_BODY = "MATCH_MESSAGE_INVALID_BODY",
  MATCH_THREAD_CLOSED = "MATCH_THREAD_CLOSED",

  // Invitation code errors
  INVITATION_CODE_REQUIRED = "INVITATION_CODE_REQUIRED",
  INVITATION_CODE_INVALID = "INVITATION_CODE_INVALID",
  INVITATION_CODE_EXPIRED = "INVITATION_CODE_EXPIRED",
  INVITATION_CODE_EXHAUSTED = "INVITATION_CODE_EXHAUSTED",
  INVITATION_CODE_INACTIVE = "INVITATION_CODE_INACTIVE",
  INVITATION_CODE_ALREADY_USED = "INVITATION_CODE_ALREADY_USED",
  INVITATION_CODE_NOT_FOUND = "INVITATION_CODE_NOT_FOUND",
  INVITATION_CODE_NOT_FOR_ORGANIZATION = "INVITATION_CODE_NOT_FOR_ORGANIZATION",

  // Organization errors
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_ACCESS_DENIED = "ORGANIZATION_ACCESS_DENIED",
  ORGANIZATION_ALREADY_MEMBER = "ORGANIZATION_ALREADY_MEMBER",
  ORGANIZATION_MEMBER_NOT_FOUND = "ORGANIZATION_MEMBER_NOT_FOUND",

  // User administration errors
  USER_DEACTIVATED = "USER_DEACTIVATED",
  CANNOT_MODIFY_SELF = "CANNOT_MODIFY_SELF",
  LAST_SUPER_ADMIN = "LAST_SUPER_ADMIN",
  USER_HAS_OWNED_CONTENT = "USER_HAS_OWNED_CONTENT",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USER_ALREADY_ARCHIVED = "USER_ALREADY_ARCHIVED",
  USER_IS_ARCHIVED = "USER_IS_ARCHIVED",
  USER_NOT_ARCHIVED = "USER_NOT_ARCHIVED",

  // Email delivery errors
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
}

// Base error class
export abstract class AppError extends Error {
  constructor(public code: ErrorCode, public details?: Record<string, unknown>) {
    super(code);
    this.name = this.constructor.name;
    Object.setPrototypeOf(this, new.target.prototype);
  }

  abstract get statusCode(): number;
}

// 400 Bad Request errors
export class BadRequestError extends AppError {
  get statusCode(): number {
    return 400;
  }
}

// 401 Unauthorized errors
export class UnauthorizedError extends AppError {
  get statusCode(): number {
    return 401;
  }
}

// 403 Forbidden errors
export class ForbiddenError extends AppError {
  get statusCode(): number {
    return 403;
  }
}

// 404 Not Found errors
export class NotFoundError extends AppError {
  get statusCode(): number {
    return 404;
  }
}

// 409 Conflict errors
export class ConflictError extends AppError {
  get statusCode(): number {
    return 409;
  }
}

// 429 Too Many Requests
export class TooManyRequestsError extends AppError {
  get statusCode(): number {
    return 429;
  }
}

// 500 Internal Server errors
export class InternalServerError extends AppError {
  get statusCode(): number {
    return 500;
  }
}
